import { db } from '@/config/firebase.config';
import '@/styles/globals.css';
import { doc, setDoc } from 'firebase/firestore';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
	const uploadAdvert = async () => {
		const advertRef = doc(db, 'adverts', 'my-advert');
		try {
			await setDoc(advertRef, {
				test: Math.floor(Math.random() * 1000).toString(),
			});
		} catch {
			console.log('Error writing document');
		}
	};
	uploadAdvert();
	return (
		<>
			<Head>
				<title>Facebook clone</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</>
	);
}

