import NavBar from '@/components/NavBar';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Facebook clone</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div style={{ overflowY: 'scroll', height: '1000px' }}>
				<NavBar />
			</div>
		</>
	);
}
