/**
 * Algolia mock implementation for local development
 * This file is auto-generated by the setupLocalEnvironment script
 */
import { SearchResponse } from 'algoliasearch';

// The data from the generated Algolia data file
const mockData = [
  {
    "objectID": "8225736e-2314-4270-8d8c-bfc60647d539",
    "firstName": "Terry",
    "lastName": "Paucek-Rodriguez",
    "profilePicture": "https://avatars.githubusercontent.com/u/19843930"
  },
  {
    "objectID": "f80a03ac-24f2-40b9-940f-379daad9be5c",
    "firstName": "Brandon",
    "lastName": "Jerde",
    "middleName": "Emerson",
    "profilePicture": "https://avatars.githubusercontent.com/u/48575359"
  },
  {
    "objectID": "5896fb71-4282-4c93-959f-27b5ce66e2c6",
    "firstName": "Kayla",
    "lastName": "Kulas",
    "middleName": "Nico",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1215.jpg"
  },
  {
    "objectID": "b778b7b1-bd48-4c1d-8038-3167a255e021",
    "firstName": "Kayla",
    "lastName": "Marks",
    "middleName": "Phoenix",
    "profilePicture": "https://avatars.githubusercontent.com/u/59762711"
  },
  {
    "objectID": "42766e73-1d48-45d9-b1fa-fb4b62653fe7",
    "firstName": "Nora",
    "lastName": "Schinner",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/582.jpg"
  },
  {
    "objectID": "16b8510e-5f0d-403f-8922-c441488d4bbd",
    "firstName": "Miriam",
    "lastName": "Treutel",
    "profilePicture": "https://avatars.githubusercontent.com/u/56778885"
  },
  {
    "objectID": "282e7a8f-2361-4ea7-9f5e-c1fb781586a3",
    "firstName": "Bobby",
    "lastName": "Paucek",
    "profilePicture": "https://avatars.githubusercontent.com/u/93544977"
  },
  {
    "objectID": "c513a34f-9c5d-4e93-b873-84649c9b72d8",
    "firstName": "Lynne",
    "lastName": "Kertzmann",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/503.jpg"
  },
  {
    "objectID": "463cf179-ff47-45a1-a5e1-075130951e10",
    "firstName": "Justin",
    "lastName": "Miller",
    "middleName": "Phoenix",
    "profilePicture": "https://avatars.githubusercontent.com/u/29266499"
  },
  {
    "objectID": "0cf19ff2-86c7-45b3-80db-c5a8096f808e",
    "firstName": "Carole",
    "lastName": "Weber",
    "middleName": "Ryan",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/115.jpg"
  },
  {
    "objectID": "701d2d4f-8cf8-4def-bef8-4a988eeecbcf",
    "firstName": "Calvin",
    "lastName": "Hermiston",
    "profilePicture": "https://avatars.githubusercontent.com/u/19539060"
  },
  {
    "objectID": "d0d3ad76-99be-43ee-b296-1a860ff7222b",
    "firstName": "Kristopher",
    "lastName": "Ryan",
    "middleName": "Kendall",
    "profilePicture": "https://avatars.githubusercontent.com/u/53052348"
  },
  {
    "objectID": "45474e10-b09e-469a-84f7-0887c036152a",
    "firstName": "Sophia",
    "lastName": "Brakus",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/73.jpg"
  },
  {
    "objectID": "997d5e9f-c239-49e0-9f4b-6db214c64791",
    "firstName": "Fernando",
    "lastName": "Littel",
    "profilePicture": "https://avatars.githubusercontent.com/u/90872312"
  },
  {
    "objectID": "25f9a850-2b38-4c75-b52a-f97984f860d3",
    "firstName": "Steve",
    "lastName": "Daugherty",
    "profilePicture": "https://avatars.githubusercontent.com/u/42920851"
  },
  {
    "objectID": "911bbfb0-facc-4c60-bf29-0381058b5448",
    "firstName": "Amy",
    "lastName": "Wolf",
    "middleName": "Ellis",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1008.jpg"
  },
  {
    "objectID": "1aeef692-5712-4417-a22b-7582abe34572",
    "firstName": "Cecil",
    "lastName": "Boyle",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/408.jpg"
  },
  {
    "objectID": "bafa0cfa-b227-4cb9-8208-be29b4cf23b3",
    "firstName": "Jana",
    "lastName": "Hettinger",
    "profilePicture": "https://avatars.githubusercontent.com/u/68117622"
  },
  {
    "objectID": "5212c884-f704-48a1-85f8-f4bc848eef9a",
    "firstName": "Glenn",
    "lastName": "Abernathy-Okuneva",
    "profilePicture": "https://avatars.githubusercontent.com/u/72551710"
  },
  {
    "objectID": "b37fd460-a788-40c4-b94b-23f810b903ea",
    "firstName": "Mae",
    "lastName": "Little",
    "profilePicture": "https://avatars.githubusercontent.com/u/61878203"
  },
  {
    "objectID": "34ffbf71-cb82-4f81-b3d1-2934525d0bc6",
    "firstName": "Brandy",
    "lastName": "Roberts",
    "profilePicture": "https://avatars.githubusercontent.com/u/45983333"
  },
  {
    "objectID": "3822d33e-1de9-42f3-abc6-3607a4964215",
    "firstName": "Van",
    "lastName": "Reinger",
    "middleName": "Robin",
    "profilePicture": "https://avatars.githubusercontent.com/u/97411148"
  },
  {
    "objectID": "0ce0404f-ba28-4d90-ba43-1b4eb71a2eca",
    "firstName": "William",
    "lastName": "Bins",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/604.jpg"
  },
  {
    "objectID": "04e8cb12-74b9-4396-9218-02e127097d4a",
    "firstName": "Raul",
    "lastName": "Schoen",
    "profilePicture": "https://avatars.githubusercontent.com/u/4072151"
  },
  {
    "objectID": "3c230e17-f9d1-4475-b6d1-b9e8c9380dae",
    "firstName": "Stephanie",
    "lastName": "Hettinger",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/287.jpg"
  },
  {
    "objectID": "f7d23711-4fc7-4fa9-8a5b-321f21e13ae4",
    "firstName": "Clifton",
    "lastName": "Rempel",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/320.jpg"
  },
  {
    "objectID": "7c3230a8-5a02-40c2-aa1a-23c694e2e04f",
    "firstName": "Johnathan",
    "lastName": "Raynor",
    "middleName": "Noah",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/694.jpg"
  },
  {
    "objectID": "69b9a201-6f01-478f-9f7a-8734234eff14",
    "firstName": "Jean",
    "lastName": "Langosh",
    "middleName": "Noah",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/769.jpg"
  },
  {
    "objectID": "6c53b3ee-d463-4329-b368-825afdaf2252",
    "firstName": "Gayle",
    "lastName": "Grant",
    "middleName": "Logan",
    "profilePicture": "https://avatars.githubusercontent.com/u/59840388"
  },
  {
    "objectID": "77e51568-cd21-4e8c-b94a-df057a0f4830",
    "firstName": "Leonard",
    "lastName": "Fahey",
    "middleName": "Kai",
    "profilePicture": "https://avatars.githubusercontent.com/u/89424770"
  },
  {
    "objectID": "424fe906-5079-404a-933c-4512c80d4e6a",
    "firstName": "Jeremiah",
    "lastName": "Greenfelder",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/337.jpg"
  },
  {
    "objectID": "838ad1f8-38b9-4f8f-96d0-422d4db6ad67",
    "firstName": "Colin",
    "lastName": "Dicki",
    "middleName": "Skyler",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/107.jpg"
  },
  {
    "objectID": "5ba18b4d-fbdc-4d52-83f4-5b66b40c47a2",
    "firstName": "Victoria",
    "lastName": "Schinner",
    "profilePicture": "https://avatars.githubusercontent.com/u/12140384"
  },
  {
    "objectID": "213b5776-7008-4b44-ab56-6fd1de40ac1f",
    "firstName": "Johnnie",
    "lastName": "Adams",
    "profilePicture": "https://avatars.githubusercontent.com/u/29779757"
  },
  {
    "objectID": "5fff1777-b360-4bc5-a75c-52e02f788dee",
    "firstName": "Stuart",
    "lastName": "Littel",
    "profilePicture": "https://avatars.githubusercontent.com/u/29408556"
  },
  {
    "objectID": "a4ddf5f8-0e0f-4b67-b835-335a965a0653",
    "firstName": "Kelli",
    "lastName": "Stamm",
    "profilePicture": "https://avatars.githubusercontent.com/u/63595851"
  },
  {
    "objectID": "d44eb308-a693-4c86-8869-059d29b81056",
    "firstName": "Ebony",
    "lastName": "Hermiston",
    "middleName": "Alex",
    "profilePicture": "https://avatars.githubusercontent.com/u/78065230"
  },
  {
    "objectID": "130c67ff-a28e-458b-8f4a-a5729679280e",
    "firstName": "Sally",
    "lastName": "Okuneva",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/371.jpg"
  },
  {
    "objectID": "afcbfa16-c7d1-4fc9-8d22-d27dcb914616",
    "firstName": "Archie",
    "lastName": "Torp",
    "middleName": "Reign",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1200.jpg"
  },
  {
    "objectID": "affef802-43d6-4554-a4c5-10e1e240084d",
    "firstName": "Mary",
    "lastName": "Hand",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/544.jpg"
  },
  {
    "objectID": "b5f74f5c-de99-4f7a-9db5-e6cb38d0d893",
    "firstName": "Juan",
    "lastName": "Ortiz",
    "profilePicture": "https://avatars.githubusercontent.com/u/81431783"
  },
  {
    "objectID": "8b65acee-e56e-46b2-832c-01606c44d626",
    "firstName": "Nathaniel",
    "lastName": "Bruen",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/71.jpg"
  },
  {
    "objectID": "8e083a74-620c-47c2-8bf0-a8fe2fb06405",
    "firstName": "Dallas",
    "lastName": "Schultz",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/824.jpg"
  },
  {
    "objectID": "0014c30f-423d-466d-b828-f35c72a38f86",
    "firstName": "Kristine",
    "lastName": "Rice",
    "profilePicture": "https://avatars.githubusercontent.com/u/74248604"
  },
  {
    "objectID": "3f5950a5-25f1-4c4e-88a9-2a8511870f9c",
    "firstName": "Tracy",
    "lastName": "Hills",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/862.jpg"
  },
  {
    "objectID": "78d829e0-0d31-40b8-8f06-7571dfa9803a",
    "firstName": "Pete",
    "lastName": "Nikolaus",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/511.jpg"
  },
  {
    "objectID": "de6c685b-2a24-4b08-9f0d-cb6d50e2d2a3",
    "firstName": "Alison",
    "lastName": "Wyman",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1091.jpg"
  },
  {
    "objectID": "ac50e5dd-dff5-45ff-9493-0cb57a6aa5aa",
    "firstName": "Hattie",
    "lastName": "Bradtke",
    "middleName": "Jules",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1103.jpg"
  },
  {
    "objectID": "bb913e4b-3700-4e94-870e-e4f0a877a41e",
    "firstName": "Tricia",
    "lastName": "Cremin",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/230.jpg"
  },
  {
    "objectID": "a3cf6d1e-44ab-4f6e-932b-593d4fd983ea",
    "firstName": "Margarita",
    "lastName": "Orn",
    "middleName": "London",
    "profilePicture": "https://avatars.githubusercontent.com/u/276585"
  },
  {
    "objectID": "d3c52ed7-bde8-4b8b-ad5b-ed91e93ce72a",
    "firstName": "Rosalie",
    "lastName": "Reichel",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/945.jpg"
  },
  {
    "objectID": "a0558614-42a4-4940-b06e-fe5d4e028939",
    "firstName": "Ginger",
    "lastName": "Hilpert",
    "profilePicture": "https://avatars.githubusercontent.com/u/21718792"
  },
  {
    "objectID": "d6f32ce3-814b-45a1-aab8-d277ec37231a",
    "firstName": "Vivian",
    "lastName": "Quitzon",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/354.jpg"
  },
  {
    "objectID": "e893fe26-2077-4169-9c82-63fc40efa9f8",
    "firstName": "Lorene",
    "lastName": "Heller",
    "profilePicture": "https://avatars.githubusercontent.com/u/27653080"
  },
  {
    "objectID": "157ead02-cbfa-45f3-b0ea-b3d9f5ab0e15",
    "firstName": "Enrique",
    "lastName": "Nader",
    "middleName": "Ryan",
    "profilePicture": "https://avatars.githubusercontent.com/u/27520083"
  },
  {
    "objectID": "da6e8a01-a2a1-4daf-a772-e858d0fb43aa",
    "firstName": "Janice",
    "lastName": "Zieme",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg"
  },
  {
    "objectID": "f2be7cb3-40c7-4577-9e85-5ffe01efec58",
    "firstName": "William",
    "lastName": "Grimes",
    "profilePicture": "https://avatars.githubusercontent.com/u/77734544"
  },
  {
    "objectID": "ae6d944a-8bff-4d9b-b6e6-4e43742e030e",
    "firstName": "Marilyn",
    "lastName": "Mueller",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/830.jpg"
  },
  {
    "objectID": "b8bb35a9-36ad-4486-b234-a97e91df3c6a",
    "firstName": "Gregg",
    "lastName": "Baumbach",
    "profilePicture": "https://avatars.githubusercontent.com/u/75641643"
  },
  {
    "objectID": "e12fdae6-bc33-4f23-82d6-8fc5efe0e381",
    "firstName": "Shari",
    "lastName": "Heaney",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/81.jpg"
  },
  {
    "objectID": "34d51831-a41f-498d-9dd6-5bf70b2b23ea",
    "firstName": "Darla",
    "lastName": "Stracke",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/769.jpg"
  },
  {
    "objectID": "8b1820a1-aa01-415c-9b6b-c54ff65f743d",
    "firstName": "Charlie",
    "lastName": "McGlynn",
    "profilePicture": "https://avatars.githubusercontent.com/u/37201824"
  },
  {
    "objectID": "190e1099-53b9-4c71-9497-6ee69a6a10bf",
    "firstName": "Jonathan",
    "lastName": "O'Keefe",
    "profilePicture": "https://avatars.githubusercontent.com/u/23219998"
  },
  {
    "objectID": "e9ddc99d-9c56-417c-900e-9dd1ec17e35f",
    "firstName": "Clyde",
    "lastName": "MacGyver",
    "profilePicture": "https://avatars.githubusercontent.com/u/80858255"
  },
  {
    "objectID": "9f0d5009-e2b7-4f9b-b19d-07b3569af2a0",
    "firstName": "Trevor",
    "lastName": "Lemke",
    "middleName": "Reagan",
    "profilePicture": "https://avatars.githubusercontent.com/u/94161540"
  },
  {
    "objectID": "853cd0a0-2823-4920-bf08-62d5acaab720",
    "firstName": "Jaime",
    "lastName": "Romaguera",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/804.jpg"
  },
  {
    "objectID": "72208e37-ad5b-4764-a6e2-033cf78a6c95",
    "firstName": "Norman",
    "lastName": "Jacobs",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/916.jpg"
  },
  {
    "objectID": "5ecea3da-2f20-4078-ba08-6fff7fb8ffaa",
    "firstName": "Jerry",
    "lastName": "Schmidt",
    "middleName": "Billie",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/481.jpg"
  },
  {
    "objectID": "6d749865-68d1-48e8-be2e-0738dd5eafa8",
    "firstName": "Shannon",
    "lastName": "O'Connell",
    "profilePicture": "https://avatars.githubusercontent.com/u/57923613"
  },
  {
    "objectID": "3a4b2cf3-0d43-4b78-b686-237e135ac151",
    "firstName": "Cecelia",
    "lastName": "Gutkowski",
    "profilePicture": "https://avatars.githubusercontent.com/u/49499425"
  },
  {
    "objectID": "f4878519-5ee8-4029-99fe-2a6192a328c8",
    "firstName": "Sheldon",
    "lastName": "Hane",
    "profilePicture": "https://avatars.githubusercontent.com/u/95322604"
  },
  {
    "objectID": "379a0415-9b66-4797-9dfe-84a9010ab641",
    "firstName": "Simon",
    "lastName": "Schmitt",
    "middleName": "Skyler",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/0.jpg"
  },
  {
    "objectID": "c9e77ee4-0a8a-4c3a-b902-f94749a617f6",
    "firstName": "Ricardo",
    "lastName": "Sawayn",
    "middleName": "Kendall",
    "profilePicture": "https://avatars.githubusercontent.com/u/83032048"
  },
  {
    "objectID": "e6caddc0-c0e9-48f1-9d9c-d2da219f1aaf",
    "firstName": "Anita",
    "lastName": "Zemlak",
    "profilePicture": "https://avatars.githubusercontent.com/u/30982518"
  },
  {
    "objectID": "e483f64b-e587-4204-a33d-48bf8cfd1eba",
    "firstName": "Lloyd",
    "lastName": "Keebler",
    "profilePicture": "https://avatars.githubusercontent.com/u/67587284"
  },
  {
    "objectID": "b6d3f2a7-ea2d-4c7e-ac2e-6614585a32f9",
    "firstName": "Paulette",
    "lastName": "Swift",
    "middleName": "Riley",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1112.jpg"
  },
  {
    "objectID": "552557ef-6449-4bad-bcd0-e1dfcb827ebe",
    "firstName": "Ricky",
    "lastName": "Hyatt",
    "middleName": "Nico",
    "profilePicture": "https://avatars.githubusercontent.com/u/27777389"
  },
  {
    "objectID": "7a44cb14-7808-4eff-9272-a19834a8ed30",
    "firstName": "Spencer",
    "lastName": "Dare",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/969.jpg"
  },
  {
    "objectID": "265e087e-f8ca-4213-9ccf-028c969b342a",
    "firstName": "John",
    "lastName": "Pfeffer",
    "middleName": "Elliott",
    "profilePicture": "https://avatars.githubusercontent.com/u/21310702"
  },
  {
    "objectID": "2138d3ff-29d6-42c9-bd61-1f2c0c0c4d16",
    "firstName": "Nina",
    "lastName": "Roob",
    "profilePicture": "https://avatars.githubusercontent.com/u/5643937"
  },
  {
    "objectID": "18d0dbb3-eb35-4a6a-b54c-a5b9d4e7b635",
    "firstName": "Debra",
    "lastName": "Blick",
    "profilePicture": "https://avatars.githubusercontent.com/u/9762732"
  },
  {
    "objectID": "b7f357e2-f2d2-40c5-a4c6-c6b47b5f2f63",
    "firstName": "Phyllis",
    "lastName": "Stoltenberg",
    "middleName": "Riley",
    "profilePicture": "https://avatars.githubusercontent.com/u/25470288"
  },
  {
    "objectID": "ba31ad1b-2a7a-4ef5-8de1-09496832d537",
    "firstName": "Bertha",
    "lastName": "Blanda",
    "profilePicture": "https://avatars.githubusercontent.com/u/71269"
  },
  {
    "objectID": "75b2018f-b7ad-45c6-a416-95dfd82e3a7f",
    "firstName": "Pauline",
    "lastName": "Green",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/178.jpg"
  },
  {
    "objectID": "92e8f356-951f-47e3-adea-f337b177a5dd",
    "firstName": "Kara",
    "lastName": "Kunde",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/344.jpg"
  },
  {
    "objectID": "ffa9656d-4cfe-417c-a425-409242b94b3f",
    "firstName": "Kate",
    "lastName": "West",
    "profilePicture": "https://avatars.githubusercontent.com/u/6507620"
  },
  {
    "objectID": "5b7c6514-d550-45e7-a92d-8404b1247662",
    "firstName": "Samantha",
    "lastName": "Shanahan",
    "middleName": "Angel",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/737.jpg"
  },
  {
    "objectID": "59f9dcc6-2b02-4fd4-acf8-4ef86c83b5a3",
    "firstName": "Noah",
    "lastName": "Oberbrunner",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/290.jpg"
  },
  {
    "objectID": "88eb0e0e-cc26-41bb-8871-21cf18bbed1f",
    "firstName": "Moses",
    "lastName": "Swaniawski",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1165.jpg"
  },
  {
    "objectID": "e1d9104a-eff9-4b24-a0c2-b7c3e69126e8",
    "firstName": "Alexandra",
    "lastName": "MacGyver",
    "middleName": "North",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/250.jpg"
  },
  {
    "objectID": "a7cbb7b0-cd33-4068-bf82-44bd786c38b7",
    "firstName": "Albert",
    "lastName": "McKenzie",
    "profilePicture": "https://avatars.githubusercontent.com/u/20797403"
  },
  {
    "objectID": "a4cb2d67-da86-4c7d-bf39-1c806a57b5b4",
    "firstName": "Diane",
    "lastName": "Zieme",
    "middleName": "Greer",
    "profilePicture": "https://avatars.githubusercontent.com/u/97725170"
  },
  {
    "objectID": "2195586c-f025-479e-90e2-268345c23a4b",
    "firstName": "Brittany",
    "lastName": "Rempel",
    "profilePicture": "https://avatars.githubusercontent.com/u/52698954"
  },
  {
    "objectID": "1be78c96-b178-45b6-be5e-1a231179081c",
    "firstName": "James",
    "lastName": "Purdy",
    "profilePicture": "https://avatars.githubusercontent.com/u/80252179"
  },
  {
    "objectID": "b8ebf7a0-59da-4890-a1df-27f03fa4843c",
    "firstName": "Bonnie",
    "lastName": "Stanton",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1147.jpg"
  },
  {
    "objectID": "0ec5cb9b-f0ba-44e7-bbee-e8fbee1ac55c",
    "firstName": "Vickie",
    "lastName": "Morar",
    "profilePicture": "https://avatars.githubusercontent.com/u/42329214"
  },
  {
    "objectID": "4e9b103b-ab77-439e-bbe3-acc2abd33231",
    "firstName": "Jerald",
    "lastName": "Dickinson",
    "middleName": "Kyle",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/782.jpg"
  },
  {
    "objectID": "65eb2205-63e2-4c32-8a9e-14422a1e2abf",
    "firstName": "Irving",
    "lastName": "Green",
    "middleName": "August",
    "profilePicture": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/850.jpg"
  },
  {
    "objectID": "20790ca0-e70c-4c3c-828c-ed7e3b6ebeed",
    "firstName": "Emma",
    "lastName": "Spinka",
    "profilePicture": "https://avatars.githubusercontent.com/u/57947535"
  },
  {
    "objectID": "03be1879-e7f3-4265-8b02-ef8c0ec9d982",
    "firstName": "Kirk",
    "lastName": "Swaniawski",
    "profilePicture": "https://avatars.githubusercontent.com/u/56769909"
  }
];

// Mock search function that filters based on search query
export function mockAlgoliaSearch(query: string): Promise<SearchResponse<any>> {
  const hits = query
    ? mockData.filter(item => {
        const searchText = `${item.firstName} ${item.middleName || ''} ${item.lastName}`.toLowerCase();
        return searchText.includes(query.toLowerCase());
      })
    : [...mockData];

  return Promise.resolve({
    hits,
    nbHits: hits.length,
    page: 0,
    nbPages: 1,
    hitsPerPage: hits.length,
    exhaustiveNbHits: true,
    query,
    params: '',
    processingTimeMS: 1,
    processingTimingsMS: {
      afterFetch: {
        total: 1
      },
      request: {
        roundTrip: 1
      }
    }
  });
}

// Mock init function
export function mockAlgoliaInit(): { search: typeof mockAlgoliaSearch } {
  return {
    search: mockAlgoliaSearch
  };
}
